server:
  port: 9093


spring:
  application:
    name: authGateWay
  cloud:
    gateway:
      routes:
        # Booking Service APIs
        - id: BOOKING
          uri: lb://BOOKING
          predicates:
            - Path=/api/v1/booking/**
          filters: []

