server:
  port: 8899

spring:
  application:
    name: eurekaServer
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/bookings/**
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**

    eureka:
      client:
        register-with-eureka: true
        fetch-registry: true
      instance:
        prefer-ip-address: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
